train_annotation: datasets/annotations/train.json
test_annotation: datasets/annotations/test.json
val_annotation: datasets/annotations/val.json

train_gebd_proposals: datasets/annotations/trainset_gebd_proposals.json
test_gebd_proposals: datasets/annotations/testset_gebd_proposals.json
val_gebd_proposals: datasets/annotations/valset_gebd_proposals.json

train_timestamps: datasets/annotations/trainset_sampled_timestamp.json
test_timestamps: datasets/annotations/testset_sampled_timestamp.json
val_timestamps: datasets/annotations/valset_sampled_timestamp.json

train_location_gt: datasets/annotations/trainset_location_gt.json
test_location_gt: datasets/annotations/testset_location_gt.json
val_location_gt: datasets/annotations/valset_location_gt.json

region_feature_root: datasets/features/region_feature
action_feature_root: datasets/features/tsn_captioning_feature
action_gebd_feature_root: datasets/features/tsn_gebd_feature
action_feature_1s_root: datasets/features/tsn_all1s_feature